/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BaseCard: typeof import('./components/default/BaseCard.vue')['default']
    BaseModal: typeof import('./components/default/BaseModal.vue')['default']
    BaseSnackbar: typeof import('./components/default/BaseSnackbar.vue')['default']
    ChangePasswordModal: typeof import('./components/modal/ChangePasswordModal.vue')['default']
    ClickCard: typeof import('./components/ClickCard.vue')['default']
    ComparativeOperationsChart: typeof import('./components/ComparativeOperationsChart.vue')['default']
    DeleteTenantModal: typeof import('./components/modal/DeleteTenantModal.vue')['default']
    DeleteUserModal: typeof import('./components/modal/DeleteUserModal.vue')['default']
    EditTenantModal: typeof import('./components/modal/EditTenantModal.vue')['default']
    EditUserModal: typeof import('./components/modal/EditUserModal.vue')['default']
    EntradasDespesasChart: typeof import('./components/EntradasDespesasChart.vue')['default']
    FiltroPeriodo: typeof import('./components/FiltroPeriodo.vue')['default']
    GlobalSnackbar: typeof import('./components/Default/GlobalSnackbar.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ReceitasDespesasChart: typeof import('./components/charts/financeiro/ReceitasDespesasChart.vue')['default']
    RecoverPasswordModal: typeof import('./components/modal/RecoverPasswordModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/default/Sidebar.vue')['default']
    SimpleDonutChart: typeof import('./components/SimpleDonutChart.vue')['default']
    SummaryCard: typeof import('./components/SummaryCard.vue')['default']
    SystemTable: typeof import('./components/SystemTable.vue')['default']
    TableComparative: typeof import('./components/TableComparative.vue')['default']
    TenantTable: typeof import('./components/TenantTable.vue')['default']
    UserMenu: typeof import('./components/default/UserMenu.vue')['default']
    UserTable: typeof import('./components/UserTable.vue')['default']
  }
}
