/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ComparativeOperationsChart: typeof import('./components/ComparativeOperationsChart.vue')['default']
    EntradasDespesasChart: typeof import('./components/EntradasDespesasChart.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HierarchicalTable: typeof import('./components/HierarchicalTable.vue')['default']
    ModalRegisterTenant: typeof import('./components/ModalRegisterTenant.vue')['default']
    ModalRegisterUser: typeof import('./components/ModalRegisterUser.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleDonutChart: typeof import('./components/SimpleDonutChart.vue')['default']
    SimpleTable: typeof import('./components/SimpleTable.vue')['default']
    SummaryCard: typeof import('./components/SummaryCard.vue')['default']
  }
}
